{% set version = "1.22" %}
{% set hash = "55423cac9e3306f4a9502c738a001e4a339d1a38ffbee7572d4a07d5d63949b2" %}

package:
  name: leveldb
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/google/leveldb/archive/{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 1

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - snappy
  run:
    - snappy

test:
  commands:
    - test -f ${PREFIX}/lib/libleveldb${SHLIB_EXT}

about:
  home: https://github.com/google/leveldb
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A fast key-value storage library providing ordered mappings.

extra:
  recipe-maintainers:
    - jakirkham
    - xhochy
