travis:
  secure:
    BINSTAR_TOKEN: UBycXqtnTp1ZpRUwHRMryUTbazqrwGJ+d/nn0eugLO9iI0E54HsXau7mj5N/jtz0SP9ghpBZVr9rl2yej3gpOMJx6Ni8r3lkfTjYDw4IXlWYWP4tCkDsoYbg+UMbbcebB2eFJwYaB+0RdghLYmSaT5veKnRzZWbR94Z2w+FYTup9AsP0wMFe81JwFxX7cCmkqZVasOml/FdCXvayQyEAQOT+bvTQnyXWpAKdOd+ePSBqJXDLqrClb13GMllsZNBb331/5ZL8dY7c689Zat+p4E+OfJtFoXvfY1Nh5DIDDlBVN1iYEWL7cFSD5ISeRznJ8KHqyL7MLnceSg9p99Y7h/RyOMr49q4nAaXWCAaKkNfVj7tHD6ZluldI97sRr/efhOXwrRiPxv+xVIephKromdezMWrygvTNcBJzyH1lvh7jA61SmgSKjXE0etohS9d3jpFEGekpmMyEObZZEr/a/LYSJ0ehdk+fvkL9F4te4W9bfKUnVFOLOpYzFU2CKUwpDs8uwY1SeVDdKVNXPD17ibHTow01fZR7a8uQgvwWWw2GTz5GUt99P2HIzh/zqxrGfTCD+RNDNmXOzfB3kUiwxi1G/jxqTXdHsf16ZrEr476e4mJBW10Czy5pyCCybSRj4TlarPqYDiQ937X8QyEZh7x/p7AMoTg4Pz3X4qRTUFc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
